version: '3'
services:
  channel-stats:
    image: thrawn01/channel-stats:latest
    command: "/channel-stats"
    environment:
      # 'token' is a bot token from a slack app. Create a slack app here
      # https://api.slack.com/apps then get the bot token from 'OAuth & Permissions'
      - STATS_SLACK_TOKEN=xoxb-123421354-fake
      # Enable debug logging
      - STATS_DEBUG=false
      # Must be true for notification to work
      - STATS_MG_ENABLED=false
      # Use the Mailgun 'Private API key' found here
      # https://app.mailgun.com/app/account/security under 'Security'
      - STATS_MG_API_KEY=key-1q23412351235123512
      # Name of verified domain you have registered with mailgun
      - STATS_MG_DOMAIN=your.domain.com
      # The email address of the operator of the bot
      - STATS_MG_OPERATOR_ADDR=admin@your.domain.com
      # The email address reports are sent to (Could be an mailing list address)
      - STATS_MG_REPORT_ADDR=my-name@your.domain.com
      # The from email address given when sending operator emails
      - STATS_MG_FROM=channel-stats@your.odmain.com
      # Timeout for network operations when talking to mailgun
      # (See http://golang.org/pkg/time/#ParseDuration for string format)
      - STATS_MG_TIMEOUT=20s
      # Location of the database on disk, should be changed if you
      # wish to persist the data to a mounted directory
      - STATS_STORE_DATA_DIR=/badger-db
      # Size of the store internal cache
      - STATS_STORE_CACHE_SIZE=100
      # Duration cached data will stay in the cache
      - STATS_STORE_CACHE_TTL=30s
      # The cron like string the dictates when reports are sent to users
      # (See https://godoc.org/github.com/robfig/cron#hdr-CRON_Expression_Format)
      - STATS_REPORT_SCHEDULE="0 0 0 * * SUN"
      # The duration used to decide the start and end hour of the report
      # (See http://golang.org/pkg/time/#ParseDuration for string format)
      - STATS_REPORT_DURATION=168h
    ports:
      - "2020:2020"
